#==============================================================================
exe/utest_Factorial.exe: utest_Factorial.cpp Factorial.h
	@mkdir -p exe
	g++ -I.. -std=c++0x -g -Wall -Werror $< -o $@

