language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
install:
  - sudo apt-get install -qq g++-4.8
  - alias g++=g++4.8
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4
  - alias clang++=clang3.4

script: chmod +x ./test.sh && ./test.sh
